// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ExemploSpecFlow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Google Search", new string[] {
            "Browser_Chrome",
            "Browser_Firefox",
            "Browser_IE"}, Description="\tAcessar o site de busca do Google e pesquisar por alguns termos", SourceFile="Features\\GoogleSearch.feature", SourceLine=3)]
    public partial class GoogleSearchFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Google Search", "\tAcessar o site de busca do Google e pesquisar por alguns termos", ProgrammingLanguage.CSharp, new string[] {
                        "Browser_Chrome",
                        "Browser_Firefox",
                        "Browser_IE"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void Pesquisar(string termo, string link, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar", null, exampleTags);
            this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
            testRunner.Given("que o usuário acesse o link \'https://google.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.And(string.Format("informe o termo \'{0}\' para ser pesquisado", termo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
            testRunner.When("a tecla Enter for pressionada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then(string.Format("o resultado será apresentado na primeira posição com o \'{0}\'", link), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Pesquisar, SpecFlow", SourceLine=13)]
        public virtual void Pesquisar_SpecFlow()
        {
            this.Pesquisar("SpecFlow", "specflow.org", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Pesquisar, Gherkin", SourceLine=13)]
        public virtual void Pesquisar_Gherkin()
        {
            this.Pesquisar("Gherkin", "cucumber.io/docs/gherkin", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Pesquisar, Cucumber", SourceLine=13)]
        public virtual void Pesquisar_Cucumber()
        {
            this.Pesquisar("Cucumber", "cucumber.io", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Pesquisar, Selenium", SourceLine=13)]
        public virtual void Pesquisar_Selenium()
        {
            this.Pesquisar("Selenium", "seleniumhq.org", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
